//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes a ringing timer and prepares for a new session.
        /// </summary>
        internal static string MainWindow_CreateJumpList_Mutes_a_ringing_timer_and_prepares_for_a_new_session {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Mutes_a_ringing_timer_and_prepares_for_a_new_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Session.
        /// </summary>
        internal static string MainWindow_CreateJumpList_Start_New_Session {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Start_New_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Timer.
        /// </summary>
        internal static string MainWindow_CreateJumpList_Start_Timer {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Start_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a new Pomodoro-session..
        /// </summary>
        internal static string MainWindow_CreateJumpList_Starts_a_new_Pomodoro_session_ {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Starts_a_new_Pomodoro_session_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the timer if it is stopped..
        /// </summary>
        internal static string MainWindow_CreateJumpList_Starts_the_timer_if_it_is_stopped_ {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Starts_the_timer_if_it_is_stopped_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Ringing.
        /// </summary>
        internal static string MainWindow_CreateJumpList_Stop_Ringing {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Stop_Ringing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Timer.
        /// </summary>
        internal static string MainWindow_CreateJumpList_Stop_Timer {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Stop_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the timer if it is started..
        /// </summary>
        internal static string MainWindow_CreateJumpList_Stops_the_timer_if_it_is_started_ {
            get {
                return ResourceManager.GetString("MainWindow_CreateJumpList_Stops_the_timer_if_it_is_started_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MainWindow_TimerTick_minutes {
            get {
                return ResourceManager.GetString("MainWindow_TimerTick_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Ringing!.
        /// </summary>
        internal static string MainWindow_TimerTick_Stop_Ringing_ {
            get {
                return ResourceManager.GetString("MainWindow_TimerTick_Stop_Ringing_", resourceCulture);
            }
        }
    }
}
